### ISSUE TITLE
Several issues with this role

### ISSUE THREAD

**Issue by nqb** [vmware/ansible-role-ovftool#12]
I try to use this role to install  `VMware-ovftool-4.4.0-15722219-lin.x86_64.bundle` on a Debian 10 server with following inventory file:
```yaml
---
download_site: 'https://packetfence.org/downloads/PacketFence/utils'

# The ovftool binary to download.
ovf_zip: 'VMware-ovftool-4.4.0-15722219-lin.x86_64.bundle'

# The MD5 hash of the binary to download.
ovf_zip_md5: '00cdec1f37600b933c20fe6506da9a3e'

# The directory into which to install the downloaded ovftool binaries.
ovf_dir: '/usr/local/bin'
```

Issues:
- at end of role execution `ovftool` is installed in `/usr/bin` in place of `ovf_dir`
- role is not idempotent because conditionals expect to find `ovftool` binary in:
https://github.com/vmware-archive/ansible-role-ovftool/blob/4286002e9d997c53a009e8d83d6abc5593b60b2a/tasks/main.yml#L25
which is wrong. Consequently, `ovftool` is reinstalled each time you run your playbook.
